Input Component
thaynnara007/ClubeWinx_frontend pull request #27
Opened 2021-07-03 17:05 UTC by gabrielvba

2021-07-03 18:17 UTC, thaynnara007 requested changes

2021-07-03 18:17 UTC, thaynnara007 commented on homemate/src/components/input/index.js
> +      <input style={styles}
```suggestion
      <input className='input-box-style'
```

2021-07-03 18:17 UTC, thaynnara007 commented on homemate/src/components/input/index.js
> +        className='field'
```suggestion
       style={styles}
```

2021-07-03 18:17 UTC, thaynnara007 commented on homemate/src/components/input/input.css
> +input{
```suggestion
.input-box-style{
```

2021-07-03 18:17 UTC, thaynnara007 commented on homemate/src/components/input/index.js
> +      <label>{name}</label>
```suggestion
      <label className="input-label">{name}</label>
```

2021-07-03 18:17 UTC, thaynnara007 commented on homemate/src/components/input/input.css
> +label {
```suggestion
.input-label {
```

2021-07-03 18:17 UTC, thaynnara007 commented on homemate/src/components/input/input.css
> +  border: 1px solid fade(white, 40%);
```suggestion

```

2021-07-03 18:17 UTC, thaynnara007 commented on homemate/src/components/input/input.css
> +  background-color: fade(white, 20%);
```suggestion
```

2021-07-03 18:17 UTC, thaynnara007 commented on homemate/src/components/input/input.css
> +  outline: 0;
```suggestion
  outline: 0;
  opacity: 70%;
```

2021-07-03 20:53 UTC, thaisnat requested changes

2021-07-03 20:53 UTC, thaisnat commented on homemate/src/components/inputTag/index.js
> +    if(tag != children) {
if(tag !== children) {

2021-07-03 20:53 UTC, thaisnat commented on homemate/src/components/inputTag/index.js
> +  const [tagValue, setTagValue] = useState(truncateTag(children));
const [tagValue, setTagValue] = useState(null);

2021-07-03 20:53 UTC, thaisnat commented on homemate/src/components/inputTag/index.js
> +
truncateTag(children);

2021-07-03 20:53 UTC, thaisnat commented on homemate/src/components/input/index.js
> +import './input.css';
/* eslint-disable react/button-has-type */
import '.input.css';

2021-07-03 20:53 UTC, thaisnat commented on homemate/src/components/input/index.js
> +      <label className="input-label">{name}</label>
<label className="input-label">{name}

2021-07-03 20:53 UTC, thaisnat commented on homemate/src/components/input/index.js
> +    </div>
</label></div>

2021-07-03 21:06 UTC, thaynnara007 requested changes

2021-07-03 21:06 UTC, thaynnara007 commented on homemate/src/components/inputTag/index.js
> +  const { children, clickTag, styles } = props;
```suggestion
  const { children, clickTag = () => '', styles } = props;
```

2021-07-03 21:10 UTC, thaisnat requested changes

2021-07-03 21:10 UTC, thaisnat commented on homemate/src/components/inputTag/index.js
> +      {truncate || children != tagValue ? <span onClick={() => changeTag(tagValue)}>{expanseTag}</span> : ""}
```suggestion
      {truncate || children !== tagValue ? <span onClick={() => changeTag(tagValue)}>{expanseTag}</span> : ""} 
```

2021-07-03 21:10 UTC, thaisnat commented on homemate/src/components/input/index.js
> +      <label className="input-label">{name}</label>
```suggestion
      <label className="input-label">{name}
```

2021-07-03 21:10 UTC, thaisnat commented on homemate/src/components/input/index.js
> +      />
```suggestion
      />
      </label>
```

2021-07-04 12:49 UTC, thaynnara007 requested changes

2021-07-04 12:49 UTC, thaynnara007 commented on homemate/src/components/inputTag/index.js
> +  }
```suggestion
    const truncateTag = (tag) => {
      if(tag.length > 10) { 
        return  tag.slice(0,9)
      } else {
        return tag;
      }
  }
```

2021-07-04 12:49 UTC, thaynnara007 commented on homemate/src/components/inputTag/index.js
> +truncateTag(children);
```suggestion
const changeTag = (tag) => {
    setTruncate(true);
    if(tag !== children) { 
      setTagValue(children);
      setExpanseTag('<<<');
    } else {
      setTagValue(children.slice(0,9));
      setExpanseTag('(...)');
    }
  }

  truncateTag(children);
```

2021-07-04 18:59 UTC, thaynnara007 approved these changes

2021-07-04 19:11 UTC, merged