Text Component
thaynnara007/ClubeWinx_frontend pull request #28
Opened 2021-07-03 17:12 UTC by thaisnat

2021-07-03 17:24 UTC, thaynnara007 commented on homemate/src/components/text/text.css
> +    font-family: 'Arial';
Coloca uma fonte mais bonita do que a arial. Se ficar em duvida entre algumas, pergunta no grupo qual preferem.

2021-07-03 17:35 UTC, thaynnara007 commented on homemate/src/components/text/text.css
> +.style{
```suggestion
.font-text-style{
```

2021-07-03 17:35 UTC, thaynnara007 commented on homemate/src/components/text/index.js
> +import style from './text.css';
```suggestion
import './text.css';
```

2021-07-03 17:35 UTC, thaynnara007 commented on homemate/src/components/text/index.js
> +        <p styles={styles={style}, styles}>{children}</p>
```suggestion
        <p className="text-font-style" style={styles}>{children}</p>
```

2021-07-03 17:47 UTC, thaisnat commented on homemate/src/components/text/text.css
> +    font-family: 'Arial';
Ok.

2021-07-03 18:39 UTC, thaynnara007 requested changes

2021-07-03 18:39 UTC, thaynnara007 commented on homemate/src/components/text/index.js
> +        <p className='style-text' styles={styles}>{children}</p>
```suggestion
        <p className='style-text' style={styles}>{children}</p>
```

2021-07-03 19:31 UTC, thaynnara007 approved these changes

2021-07-04 00:35 UTC, gabrielvba approved these changes
ok

2021-07-04 00:35 UTC, merged