Post details
thaynnara007/ClubeWinx_frontend pull request #35
Opened 2021-07-09 04:06 UTC by wesleysan7os

Link entre os posts e suas respectivas páginas de detalhamento.

![Captura de tela 2021-07-09 010105_LI](https://user-images.githubusercontent.com/12885110/125021881-e2faeb80-e051-11eb-9c4f-35afb0d502fd.jpg)
![Captura de tela 2021-07-09 010242](https://user-images.githubusercontent.com/12885110/125021907-ebebbd00-e051-11eb-8ba2-070ec24ffbf9.png)

2021-07-09 19:02 UTC, thaynnara007 requested changes

2021-07-09 19:02 UTC, thaynnara007 commented on homemate/src/components/flipCard/flipCardBack/index.js
> +import { Link } from 'react-router-dom';
```suggestion
import { useHistory } from 'react-router-dom';
```

2021-07-09 19:02 UTC, thaynnara007 commented on homemate/src/components/flipCard/flipCardBack/index.js
>  }) {
```suggestion
}) {
  const history = useHistory()
```

2021-07-09 19:02 UTC, thaynnara007 commented on homemate/src/components/flipCard/flipCardBack/index.js
> +          ;
```suggestion
    
        <button 
            className="flip-card-back-button flip-card-back-button-see-page"
            onClick={() => history.push(`/posts/${id}`)}
            >
            {seePageButton}
        </button>

```

2021-07-09 19:03 UTC, thaynnara007 commented on homemate/src/components/flipCard/flipCardBack/index.js
> +          ;
o Link tava quebrando o estilo do botão

2021-07-09 23:46 UTC, thaynnara007 approved these changes

2021-07-10 01:27 UTC, thaisnat approved these changes
Rota de detalhes conferida.

2021-07-10 02:06 UTC, gabrielvba approved these changes

2021-07-10 20:59 UTC, marianaalucena approved these changes

2021-07-10 21:02 UTC, merged