Create post
thaynnara007/ClubeWinx_frontend pull request #43
Opened 2021-07-16 14:49 UTC by marianaalucena

![image](https://user-images.githubusercontent.com/20727725/125966396-94070bec-cf39-4f65-ab53-57615a911897.png)

2021-07-16 14:50 UTC, wesleysan7os approved these changes

2021-07-16 18:35 UTC, thaynnara007 requested changes

2021-07-16 18:35 UTC, thaynnara007 commented on homemate/src/components/addTag/index.js
> +function AddTag({ toLogin }) {
```suggestion
function AddTag() {
```

2021-07-16 18:35 UTC, thaynnara007 commented on homemate/src/components/addTag/index.js
> +function AddTag({ toLogin }) {
não está sendo usado.

2021-07-16 18:35 UTC, thaynnara007 commented on homemate/src/pages/createPost/index.js
> +            <AddTag toLogin={handleClickCreatePost} />
```suggestion
            <AddTag />
```

Não está sendo usado.

2021-07-16 18:35 UTC, thaynnara007 commented on homemate/src/pages/createPost/index.js
> +          actions={[handleClickCreatePost, handleClickAddTag]}
```suggestion
          actions={[() => {}, handleClickCreatePost, handleClickAddTag]}
```
Para entrar na aba de tags, eu tinha que clicar me CRIAR ANUNCIO, e depois n tinha ocmo voltar par a aba de criar anúncio. isso resolve esse bug

2021-07-16 18:35 UTC, thaynnara007 commented on homemate/src/components/newPost/newPost.css
> +}
Deleta este arquivo, ele não está sendo utilizado, alem de conter apenas repetição de código.

2021-07-16 18:35 UTC, thaynnara007 commented on homemate/src/pages/createPost/index.js
> +      <IconArrowLeft styles={{ zIndex: 4, color: '#FFFFFF' }} />
```suggestion
      <IconArrowLeft styles={{  color: '#FFFFFF' }} />
```

2021-07-16 18:35 UTC, thaynnara007 commented on homemate/src/pages/createPost/index.js
> +      className="profile-icon-button"
```suggestion
      className="arrow-left-icon-button"
```

2021-07-16 18:35 UTC, thaynnara007 commented on homemate/src/pages/createPost/index.js
> +    <div className="createPost-background">
```suggestion
    <div className="homepage-background createPost-background">
```

2021-07-16 18:35 UTC, thaynnara007 commented on homemate/src/pages/createPost/createPost.css
> +}
```suggestion
.createPost-background {
  background-image: linear-gradient(40deg, rgba(83, 103, 189, 0.7), rgba(244, 244, 244, 0.7)),
    url('https://images.unsplash.com/photo-1529408686214-b48b8532f72c?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=986e2dee5c1b488d877ad7ba1afaf2ec&auto=format&fit=crop&w=1350&q=80');
}

.arrow-left-icon-button {
  border: none;
  background-color: transparent;
}
```

2021-07-16 18:35 UTC, thaynnara007 commented on homemate/src/pages/createPost/index.js
> +          alt="homemate's logo"
```suggestion
          alt="homemate's logo"
          style={{ cursor: 'pointer'}}
```

2021-07-16 18:35 UTC, thaynnara007 commented on homemate/src/components/newPost/index.js
> +export default NewPost;
```suggestion
import React, { useState } from 'react';
import { toast } from 'react-toastify';
import { Tooltip } from '@material-ui/core';
import { withStyles } from '@material-ui/core/styles';

import api from '../../api';
import Input from '../input';
import BaseButton from '../button';
import Loading from '../loading';
import useFetch from '../../hooks/useFetch';

const stylesInvalid = {
  label: {
    color: 'red',
  },
};

const stylesValid = {
  label: {
    color: '#F4F4F4',
  },
};

const buttonStyle = { width: '100%', fontWeight: 'bold' };
const disabledButtonStyle = { ...buttonStyle, backgroundColor: 'grey', cursor: 'not-allowed' };

const UPDATE_YOUR_ADDRESS = 'Pegaremos essa informação do seu perfil.';
const disabledButtonTip =
  'Para criar um anúncio, você precisa ter alguma informação relativa a endereço no seu';

const HtmlTooltip = withStyles(() => ({
  tooltip: {
    backgroundColor: '#F4F4F4',
    color: '#6983AA',
    maxWidth: 250,
    fontSize: '18px',
    border: '1px solid #dadde9',
  },
}))(Tooltip);

const tooltip = (
  <>
    <p>
      {disabledButtonTip}
      <b>{' perfil.'}</b>
    </p>
  </>
);

function NewPost() {
  const { data: address, isLoading } = useFetch('/address/me');

  const [expense, setExpense] = useState('');
  const [description, setDescription] = useState('');
  const [residents, setResidents] = useState('');
  const [vacancies, setVacancies] = useState('');
  const [bathrooms, setBathrooms] = useState('');
  const [beds, setBeds] = useState('');

  const [labelExpenseStyle, setLabelExpenseStyle] = useState({});
  const [labelDescriptionStyle, setLabelDescriptionStyle] = useState({});
  const [labelResidentsStyle, setLabelResidentsStyle] = useState({});
  const [labelVacanciesStyle, setLabelVacanciesStyle] = useState({});
  const [labelBathroomsStyle, setLabelBathroomsStyle] = useState({});
  const [labelBedsStyle, setLabelBedsStyle] = useState({});

  const [loading, setLoading] = useState(false);

  const validateExpense = () => {
    const validation = expense === '' || expense === null;
    setLabelExpenseStyle(validation ? stylesInvalid : stylesValid);
    return !validation;
  };

  const validateDescription = () => {
    const validation = description === '' || description === null;
    setLabelDescriptionStyle(validation ? stylesInvalid : stylesValid);
    return !validation;
  };

  const validateResidents = () => {
    const validation = residents === '' || residents === null;
    setLabelResidentsStyle(validation ? stylesInvalid : stylesValid);
    return !validation;
  };

  const validateVacancies = () => {
    const validation = vacancies === '' || vacancies === null;
    setLabelVacanciesStyle(validation ? stylesInvalid : stylesValid);
    return !validation;
  };

  const validateBathrooms = () => {
    const validation = bathrooms === '' || bathrooms === null;
    setLabelBathroomsStyle(validation ? stylesInvalid : stylesValid);
    return !validation;
  };

  const validateBeds = () => {
    const validation = beds === '' || beds === null;
    setLabelBedsStyle(validation ? stylesInvalid : stylesValid);
    return !validation;
  };

  const validateInfo = () =>
    validateExpense() &&
    validateDescription() &&
    validateResidents() &&
    validateVacancies() &&
    validateBathrooms() &&
    validateBeds();

  const validateAddress = () => {
    if (
      address &&
      address.street &&
      address.number &&
      address.district &&
      address.city &&
      address.state
    )
      return true;

    return false;
  };

  const register = () => {
    if (validateInfo()) {
      setLoading(true);

      const body = {
        expense,
        description,
        residents,
        vacancies,
        bathrooms,
        beds,
      };

      api
        .post('/user/poster', body)
        .then((response) => {
          if (response) {
            setLoading(false);

            toast('Anúncio criado com sucesso!');
          }
        })
        .catch((error) => {
          let msg = '';
          if (error.response) msg = error.response.data.error;
          else msg = 'Network failed';

          setLoading(false);
          toast.error(msg);
        });
    }
  };

  return (
    <>
      {isLoading || loading ? (
        <div style={{ marginTop: '400px' }}>
          <Loading />
        </div>
      ) : (
        <>
          <Input name="VALOR" value={expense} onChange={setExpense} styles={labelExpenseStyle} />
          <Input
            name="DESCRIÇÃO"
            value={description}
            onChange={setDescription}
            styles={labelDescriptionStyle}
          />
          <Input
            name="QUANTIDADE DE MORADORES"
            value={residents}
            onChange={setResidents}
            styles={labelResidentsStyle}
          />
          <Input
            name="QUANTIDADE DE QUARTOS"
            value={vacancies}
            onChange={setVacancies}
            styles={labelVacanciesStyle}
          />
          <Input
            name="QUANTIDADE DE BANHEIROS"
            value={bathrooms}
            onChange={setBathrooms}
            styles={labelBathroomsStyle}
          />
          <Input
            name="QUANTIDADE DE CAMAS"
            value={beds}
            onChange={setBeds}
            styles={labelBedsStyle}
          />
          <Input name="RUA" value={address?.street ?? UPDATE_YOUR_ADDRESS} onChange={() => {}} />
          <Input name="NÚMERO" value={address?.number ?? UPDATE_YOUR_ADDRESS} onChange={() => {}} />
          <Input
            name="BAIRRO"
            value={address?.district ?? UPDATE_YOUR_ADDRESS}
            onChange={() => {}}
          />
          <Input
            name="COMPLEMENTO"
            value={address?.complement ?? UPDATE_YOUR_ADDRESS}
            onChange={() => {}}
          />
          <Input name="CEP" value={address?.zipCode ?? UPDATE_YOUR_ADDRESS} onChange={() => {}} />
          <Input name="CIDADE" value={address?.city ?? UPDATE_YOUR_ADDRESS} onChange={() => {}} />
          <Input name="ESTADO" value={address?.state ?? UPDATE_YOUR_ADDRESS} onChange={() => {}} />
          {validateAddress() ? (
            <BaseButton onClick={register} styles={buttonStyle}>
              CRIAR
            </BaseButton>
          ) : (
            <HtmlTooltip title={tooltip} placement="right-end">
              <div style={{ width: '100%' }}>
                <BaseButton onClick={() => {}} styles={disabledButtonStyle}>
                  CRIAR
                </BaseButton>
              </div>
            </HtmlTooltip>
          )}
        </>
      )}
    </>
  );
}

export default NewPost;

```

2021-07-16 18:35 UTC, thaynnara007 commented on homemate/src/components/newPost/index.js
> +export default NewPost;
```suggestion
import React, { useState } from 'react';
import { toast } from 'react-toastify';
import { Tooltip } from '@material-ui/core';
import { withStyles } from '@material-ui/core/styles';

import api from '../../api';
import Input from '../input';
import BaseButton from '../button';
import Loading from '../loading';
import useFetch from '../../hooks/useFetch';

const stylesInvalid = {
  label: {
    color: 'red',
  },
};

const stylesValid = {
  label: {
    color: '#F4F4F4',
  },
};

const buttonStyle = { width: '100%', fontWeight: 'bold' };
const disabledButtonStyle = { ...buttonStyle, backgroundColor: 'grey', cursor: 'not-allowed' };

const UPDATE_YOUR_ADDRESS = 'Pegaremos essa informação do seu perfil.';
const disabledButtonTip =
  'Para criar um anúncio, você precisa ter alguma informação relativa a endereço no seu';

const HtmlTooltip = withStyles(() => ({
  tooltip: {
    backgroundColor: '#F4F4F4',
    color: '#6983AA',
    maxWidth: 250,
    fontSize: '18px',
    border: '1px solid #dadde9',
  },
}))(Tooltip);

const tooltip = (
  <>
    <p>
      {disabledButtonTip}
      <b>{' perfil.'}</b>
    </p>
  </>
);

function NewPost() {
  const { data: address, isLoading } = useFetch('/address/me');

  const [expense, setExpense] = useState('');
  const [description, setDescription] = useState('');
  const [residents, setResidents] = useState('');
  const [vacancies, setVacancies] = useState('');
  const [bathrooms, setBathrooms] = useState('');
  const [beds, setBeds] = useState('');

  const [labelExpenseStyle, setLabelExpenseStyle] = useState({});
  const [labelDescriptionStyle, setLabelDescriptionStyle] = useState({});
  const [labelResidentsStyle, setLabelResidentsStyle] = useState({});
  const [labelVacanciesStyle, setLabelVacanciesStyle] = useState({});
  const [labelBathroomsStyle, setLabelBathroomsStyle] = useState({});
  const [labelBedsStyle, setLabelBedsStyle] = useState({});

  const [loading, setLoading] = useState(false);

  const validateExpense = () => {
    const validation = expense === '' || expense === null;
    setLabelExpenseStyle(validation ? stylesInvalid : stylesValid);
    return !validation;
  };

  const validateDescription = () => {
    const validation = description === '' || description === null;
    setLabelDescriptionStyle(validation ? stylesInvalid : stylesValid);
    return !validation;
  };

  const validateResidents = () => {
    const validation = residents === '' || residents === null;
    setLabelResidentsStyle(validation ? stylesInvalid : stylesValid);
    return !validation;
  };

  const validateVacancies = () => {
    const validation = vacancies === '' || vacancies === null;
    setLabelVacanciesStyle(validation ? stylesInvalid : stylesValid);
    return !validation;
  };

  const validateBathrooms = () => {
    const validation = bathrooms === '' || bathrooms === null;
    setLabelBathroomsStyle(validation ? stylesInvalid : stylesValid);
    return !validation;
  };

  const validateBeds = () => {
    const validation = beds === '' || beds === null;
    setLabelBedsStyle(validation ? stylesInvalid : stylesValid);
    return !validation;
  };

  const validateInfo = () =>
    validateExpense() &&
    validateDescription() &&
    validateResidents() &&
    validateVacancies() &&
    validateBathrooms() &&
    validateBeds();

  const validateAddress = () => {
    if (
      address &&
      address.street &&
      address.number &&
      address.district &&
      address.city &&
      address.state
    )
      return true;

    return false;
  };

  const register = () => {
    if (validateInfo()) {
      setLoading(true);

      const body = {
        expense,
        description,
        residents,
        vacancies,
        bathrooms,
        beds,
      };

      api
        .post('/user/poster', body)
        .then((response) => {
          if (response) {
            setLoading(false);

            toast('Anúncio criado com sucesso!');
          }
        })
        .catch((error) => {
          let msg = '';
          if (error.response) msg = error.response.data.error;
          else msg = 'Network failed';

          setLoading(false);
          toast.error(msg);
        });
    }
  };

  return (
    <>
      {isLoading || loading ? (
        <div style={{ marginTop: '400px' }}>
          <Loading />
        </div>
      ) : (
        <>
          <Input name="VALOR" value={expense} onChange={setExpense} styles={labelExpenseStyle} />
          <Input
            name="DESCRIÇÃO"
            value={description}
            onChange={setDescription}
            styles={labelDescriptionStyle}
          />
          <Input
            name="QUANTIDADE DE MORADORES"
            value={residents}
            onChange={setResidents}
            styles={labelResidentsStyle}
          />
          <Input
            name="QUANTIDADE DE QUARTOS"
            value={vacancies}
            onChange={setVacancies}
            styles={labelVacanciesStyle}
          />
          <Input
            name="QUANTIDADE DE BANHEIROS"
            value={bathrooms}
            onChange={setBathrooms}
            styles={labelBathroomsStyle}
          />
          <Input
            name="QUANTIDADE DE CAMAS"
            value={beds}
            onChange={setBeds}
            styles={labelBedsStyle}
          />
          <Input name="RUA" value={address?.street ?? UPDATE_YOUR_ADDRESS} onChange={() => {}} />
          <Input name="NÚMERO" value={address?.number ?? UPDATE_YOUR_ADDRESS} onChange={() => {}} />
          <Input
            name="BAIRRO"
            value={address?.district ?? UPDATE_YOUR_ADDRESS}
            onChange={() => {}}
          />
          <Input
            name="COMPLEMENTO"
            value={address?.complement ?? UPDATE_YOUR_ADDRESS}
            onChange={() => {}}
          />
          <Input name="CEP" value={address?.zipCode ?? UPDATE_YOUR_ADDRESS} onChange={() => {}} />
          <Input name="CIDADE" value={address?.city ?? UPDATE_YOUR_ADDRESS} onChange={() => {}} />
          <Input name="ESTADO" value={address?.state ?? UPDATE_YOUR_ADDRESS} onChange={() => {}} />
          {validateAddress() ? (
            <BaseButton onClick={register} styles={buttonStyle}>
              CRIAR
            </BaseButton>
          ) : (
            <HtmlTooltip title={tooltip} placement="right-end">
              <div style={{ width: '100%' }}>
                <BaseButton onClick={() => {}} styles={disabledButtonStyle}>
                  CRIAR
                </BaseButton>
              </div>
            </HtmlTooltip>
          )}
        </>
      )}
    </>
  );
}

export default NewPost;

```

2021-07-16 18:35 UTC, thaynnara007 commented on homemate/src/components/newPost/index.js
> +export default NewPost;
```suggestion
import React, { useState } from 'react';
import { toast } from 'react-toastify';
import { Tooltip } from '@material-ui/core';
import { withStyles } from '@material-ui/core/styles';

import api from '../../api';
import Input from '../input';
import BaseButton from '../button';
import Loading from '../loading';
import useFetch from '../../hooks/useFetch';

const stylesInvalid = {
  label: {
    color: 'red',
  },
};

const stylesValid = {
  label: {
    color: '#F4F4F4',
  },
};

const buttonStyle = { width: '100%', fontWeight: 'bold' };
const disabledButtonStyle = { ...buttonStyle, backgroundColor: 'grey', cursor: 'not-allowed' };

const UPDATE_YOUR_ADDRESS = 'Pegaremos essa informação do seu perfil.';
const disabledButtonTip =
  'Para criar um anúncio, você precisa ter alguma informação relativa a endereço no seu';

const HtmlTooltip = withStyles(() => ({
  tooltip: {
    backgroundColor: '#F4F4F4',
    color: '#6983AA',
    maxWidth: 250,
    fontSize: '18px',
    border: '1px solid #dadde9',
  },
}))(Tooltip);

const tooltip = (
  <>
    <p>
      {disabledButtonTip}
      <b>{' perfil.'}</b>
    </p>
  </>
);

function NewPost() {
  const { data: address, isLoading } = useFetch('/address/me');

  const [expense, setExpense] = useState('');
  const [description, setDescription] = useState('');
  const [residents, setResidents] = useState('');
  const [vacancies, setVacancies] = useState('');
  const [bathrooms, setBathrooms] = useState('');
  const [beds, setBeds] = useState('');

  const [labelExpenseStyle, setLabelExpenseStyle] = useState({});
  const [labelDescriptionStyle, setLabelDescriptionStyle] = useState({});
  const [labelResidentsStyle, setLabelResidentsStyle] = useState({});
  const [labelVacanciesStyle, setLabelVacanciesStyle] = useState({});
  const [labelBathroomsStyle, setLabelBathroomsStyle] = useState({});
  const [labelBedsStyle, setLabelBedsStyle] = useState({});

  const [loading, setLoading] = useState(false);

  const validateExpense = () => {
    const validation = expense === '' || expense === null;
    setLabelExpenseStyle(validation ? stylesInvalid : stylesValid);
    return !validation;
  };

  const validateDescription = () => {
    const validation = description === '' || description === null;
    setLabelDescriptionStyle(validation ? stylesInvalid : stylesValid);
    return !validation;
  };

  const validateResidents = () => {
    const validation = residents === '' || residents === null;
    setLabelResidentsStyle(validation ? stylesInvalid : stylesValid);
    return !validation;
  };

  const validateVacancies = () => {
    const validation = vacancies === '' || vacancies === null;
    setLabelVacanciesStyle(validation ? stylesInvalid : stylesValid);
    return !validation;
  };

  const validateBathrooms = () => {
    const validation = bathrooms === '' || bathrooms === null;
    setLabelBathroomsStyle(validation ? stylesInvalid : stylesValid);
    return !validation;
  };

  const validateBeds = () => {
    const validation = beds === '' || beds === null;
    setLabelBedsStyle(validation ? stylesInvalid : stylesValid);
    return !validation;
  };

  const validateInfo = () =>
    validateExpense() &&
    validateDescription() &&
    validateResidents() &&
    validateVacancies() &&
    validateBathrooms() &&
    validateBeds();

  const validateAddress = () => {
    if (
      address &&
      address.street &&
      address.number &&
      address.district &&
      address.city &&
      address.state
    )
      return true;

    return false;
  };

  const register = () => {
    if (validateInfo()) {
      setLoading(true);

      const body = {
        expense,
        description,
        residents,
        vacancies,
        bathrooms,
        beds,
      };

      api
        .post('/user/poster', body)
        .then((response) => {
          if (response) {
            setLoading(false);

            toast('Anúncio criado com sucesso!');
          }
        })
        .catch((error) => {
          let msg = '';
          if (error.response) msg = error.response.data.error;
          else msg = 'Network failed';

          setLoading(false);
          toast.error(msg);
        });
    }
  };

  return (
    <>
      {isLoading || loading ? (
        <div style={{ marginTop: '400px' }}>
          <Loading />
        </div>
      ) : (
        <>
          <Input name="VALOR" value={expense} onChange={setExpense} styles={labelExpenseStyle} />
          <Input
            name="DESCRIÇÃO"
            value={description}
            onChange={setDescription}
            styles={labelDescriptionStyle}
          />
          <Input
            name="QUANTIDADE DE MORADORES"
            value={residents}
            onChange={setResidents}
            styles={labelResidentsStyle}
          />
          <Input
            name="QUANTIDADE DE QUARTOS"
            value={vacancies}
            onChange={setVacancies}
            styles={labelVacanciesStyle}
          />
          <Input
            name="QUANTIDADE DE BANHEIROS"
            value={bathrooms}
            onChange={setBathrooms}
            styles={labelBathroomsStyle}
          />
          <Input
            name="QUANTIDADE DE CAMAS"
            value={beds}
            onChange={setBeds}
            styles={labelBedsStyle}
          />
          <Input name="RUA" value={address?.street ?? UPDATE_YOUR_ADDRESS} onChange={() => {}} />
          <Input name="NÚMERO" value={address?.number ?? UPDATE_YOUR_ADDRESS} onChange={() => {}} />
          <Input
            name="BAIRRO"
            value={address?.district ?? UPDATE_YOUR_ADDRESS}
            onChange={() => {}}
          />
          <Input
            name="COMPLEMENTO"
            value={address?.complement ?? UPDATE_YOUR_ADDRESS}
            onChange={() => {}}
          />
          <Input name="CEP" value={address?.zipCode ?? UPDATE_YOUR_ADDRESS} onChange={() => {}} />
          <Input name="CIDADE" value={address?.city ?? UPDATE_YOUR_ADDRESS} onChange={() => {}} />
          <Input name="ESTADO" value={address?.state ?? UPDATE_YOUR_ADDRESS} onChange={() => {}} />
          {validateAddress() ? (
            <BaseButton onClick={register} styles={buttonStyle}>
              CRIAR
            </BaseButton>
          ) : (
            <HtmlTooltip title={tooltip} placement="right-end">
              <div style={{ width: '100%' }}>
                <BaseButton onClick={() => {}} styles={disabledButtonStyle}>
                  CRIAR
                </BaseButton>
              </div>
            </HtmlTooltip>
          )}
        </>
      )}
    </>
  );
}

export default NewPost;

```

2021-07-16 18:35 UTC, thaynnara007 commented on homemate/src/components/newPost/index.js
> +import './newPost.css';
```suggestion
import React, { useState } from 'react';
import { toast } from 'react-toastify';
import { Tooltip } from '@material-ui/core';
import { withStyles } from '@material-ui/core/styles';

import api from '../../api';
import Input from '../input';
import BaseButton from '../button';
import Loading from '../loading';
import useFetch from '../../hooks/useFetch';
```

retirando imports desnecessarios e importanto coisas q irei usar abaixo

2021-07-16 18:35 UTC, thaynnara007 commented on homemate/src/components/newPost/index.js
> +};
```suggestion
const stylesInvalid = {
  label: {
    color: 'red',
  },
};

const stylesValid = {
  label: {
    color: '#F4F4F4',
  },
};

const buttonStyle = { width: '100%', fontWeight: 'bold' };
const disabledButtonStyle = { ...buttonStyle, backgroundColor: 'grey', cursor: 'not-allowed' };

const UPDATE_YOUR_ADDRESS = 'Pegaremos essa informação do seu perfil.';
const disabledButtonTip =
  'Para criar um anúncio, você precisa ter alguma informação relativa a endereço no seu';

const HtmlTooltip = withStyles(() => ({
  tooltip: {
    backgroundColor: '#F4F4F4',
    color: '#6983AA',
    maxWidth: 250,
    fontSize: '18px',
    border: '1px solid #dadde9',
  },
}))(Tooltip);

const tooltip = (
  <>
    <p>
      {disabledButtonTip}
      <b>{' perfil.'}</b>
    </p>
  </>
);
```

2021-07-16 18:35 UTC, thaynnara007 commented on homemate/src/components/newPost/index.js
> +  const [state, setState] = useState('');
```suggestion
  const { data: address, isLoading } = useFetch('/address/me');
  
  const [expense, setExpense] = useState('');
  const [description, setDescription] = useState('');
  const [residents, setResidents] = useState('');
  const [vacancies, setVacancies] = useState('');
  const [bathrooms, setBathrooms] = useState('');
  const [beds, setBeds] = useState('');

  const [labelExpenseStyle, setLabelExpenseStyle] = useState({});
  const [labelDescriptionStyle, setLabelDescriptionStyle] = useState({});
  const [labelResidentsStyle, setLabelResidentsStyle] = useState({});
  const [labelVacanciesStyle, setLabelVacanciesStyle] = useState({});
  const [labelBathroomsStyle, setLabelBathroomsStyle] = useState({});
  const [labelBedsStyle, setLabelBedsStyle] = useState({});

  const [loading, setLoading] = useState(false);
```

2021-07-16 18:35 UTC, thaynnara007 commented on homemate/src/components/newPost/index.js
> +
```suggestion
  const validateAddress = () => {
    if (
      address &&
      address.street &&
      address.number &&
      address.district &&
      address.city &&
      address.state
    )
      return true;

    return false;
  
  };
  
  
```

2021-07-16 18:35 UTC, thaynnara007 commented on homemate/src/components/newPost/index.js
> +  };
```suggestion
  const register = () => {
    if (validateInfo()) {
      setLoading(true);

      const body = {
        expense,
        description,
        residents,
        vacancies,
        bathrooms,
        beds,
      };

      api
        .post('/user/poster', body)
        .then((response) => {
          if (response) {
            setLoading(false);

            toast('Anúncio criado com sucesso!');
          }
        })
        .catch((error) => {
          let msg = '';
          if (error.response) msg = error.response.data.error;
          else msg = 'Network failed';

          setLoading(false);
          toast.error(msg);
        });
    }
  };
```

2021-07-16 18:35 UTC, thaynnara007 commented on homemate/src/components/newPost/index.js
> +  }, []);
```suggestion

```

2021-07-16 18:35 UTC, thaynnara007 commented on homemate/src/components/newPost/index.js
> +}
```suggestion
  return (
    <>
      {isLoading || loading ? (
        <div style={{ marginTop: '400px' }}>
          <Loading />
        </div>
      ) : (
        <>
          <Input name="VALOR" value={expense} onChange={setExpense} styles={labelExpenseStyle} />
          <Input
            name="DESCRIÇÃO"
            value={description}
            onChange={setDescription}
            styles={labelDescriptionStyle}
          />
          <Input
            name="QUANTIDADE DE MORADORES"
            value={residents}
            onChange={setResidents}
            styles={labelResidentsStyle}
          />
          <Input
            name="QUANTIDADE DE QUARTOS"
            value={vacancies}
            onChange={setVacancies}
            styles={labelVacanciesStyle}
          />
          <Input
            name="QUANTIDADE DE BANHEIROS"
            value={bathrooms}
            onChange={setBathrooms}
            styles={labelBathroomsStyle}
          />
          <Input
            name="QUANTIDADE DE CAMAS"
            value={beds}
            onChange={setBeds}
            styles={labelBedsStyle}
          />
          <Input name="RUA" value={address?.street ?? UPDATE_YOUR_ADDRESS} onChange={() => {}} />
          <Input name="NÚMERO" value={address?.number ?? UPDATE_YOUR_ADDRESS} onChange={() => {}} />
          <Input
            name="BAIRRO"
            value={address?.district ?? UPDATE_YOUR_ADDRESS}
            onChange={() => {}}
          />
          <Input
            name="COMPLEMENTO"
            value={address?.complement ?? UPDATE_YOUR_ADDRESS}
            onChange={() => {}}
          />
          <Input name="CEP" value={address?.zipCode ?? UPDATE_YOUR_ADDRESS} onChange={() => {}} />
          <Input name="CIDADE" value={address?.city ?? UPDATE_YOUR_ADDRESS} onChange={() => {}} />
          <Input name="ESTADO" value={address?.state ?? UPDATE_YOUR_ADDRESS} onChange={() => {}} />
          {validateAddress() ? (
            <BaseButton onClick={register} styles={buttonStyle}>
              CRIAR
            </BaseButton>
          ) : (
            <HtmlTooltip title={tooltip} placement="right-end">
              <div style={{ width: '100%' }}>
                <BaseButton onClick={() => {}} styles={disabledButtonStyle}>
                  CRIAR
                </BaseButton>
              </div>
            </HtmlTooltip>
          )}
        </>
      )}
    </>
  );
}
```

2021-07-16 18:35 UTC, thaynnara007 commented on homemate/src/components/newPost/index.js
> +}
Não pde ser possivel criar um anúncio sem nenhum endereço, logo, um usuário que n tem nenhum endereço cadastrado n pode criar um anúncio. com essas mudanças isso é resolvido.

2021-07-19 13:07 UTC, thaynnara007 approved these changes

2021-07-19 13:19 UTC, merged