Edit profile
thaynnara007/ClubeWinx_frontend pull request #44
Opened 2021-07-19 18:39 UTC by marianaalucena

É possível acessar a tela de edição de perfil acessando o ícone de edição do perfil rsrs, como demonstrado no print abaixo

![image](https://user-images.githubusercontent.com/20727725/126210191-6efb3ed7-867f-44c4-b84f-def58cd40f06.png)

A tela final ficou assim: 

![image](https://user-images.githubusercontent.com/20727725/126210235-aca2a9d1-9def-4837-8a32-5ba32ec27de6.png)

2021-07-20 14:41 UTC, wesleysan7os approved these changes
![Captura de tela 2021-07-20 114041](https://user-images.githubusercontent.com/12885110/126343799-1ca9adcc-f5ce-4434-b697-b8a7798c995a.png)

2021-07-20 19:45 UTC, thaynnara007 requested changes

2021-07-20 19:45 UTC, thaynnara007 commented on homemate/src/pages/editProfile/editProfile.css
> +  overflow: hidden;
```suggestion

```

Isso tudo ja tem, identico, no arquivo homepage.css, sendo usado para a mesma coisa da mesma forma.

2021-07-20 19:45 UTC, thaynnara007 commented on homemate/src/pages/editProfile/editProfile.css
> +}
```suggestion
```

Isso tudo ja tem, identico, no arquivo homepage.css, sendo usado para a mesma coisa da mesma forma.

2021-07-20 19:45 UTC, thaynnara007 commented on homemate/src/pages/editProfile/index.js
> +    <div className="editProfile-background">
```suggestion
    <div className="homepage-background editProfile-background">
```

2021-07-20 19:45 UTC, thaynnara007 commented on homemate/src/components/profileEdit/index.js
> +          />
Falta alto preencher os campos. Que nem o endereço na tela de criação de anúncio.

2021-07-20 19:45 UTC, thaynnara007 commented on homemate/src/components/editRegister/index.js
> +          />
Falta alto preencher os campos. Que nem o endereço na tela de criação de anúncio.

2021-07-22 11:15 UTC, thaynnara007 approved these changes

2021-07-22 13:13 UTC, merged