Profile card
thaynnara007/ClubeWinx_frontend pull request #50
Opened 2021-07-23 23:15 UTC by wesleysan7os

![Captura de tela 2021-07-23 200348](https://user-images.githubusercontent.com/12885110/126849555-01eaa87d-bbd4-4011-9691-449a5e412662.png)

2021-07-24 12:41 UTC, thaynnara007 requested changes

2021-07-24 12:41 UTC, thaynnara007 commented on homemate/src/pages/explore/index.js
> +      .get('/profile')
usar rota dos perfis recomendados.

2021-07-24 13:40 UTC, wesleysan7os commented on homemate/src/pages/explore/index.js
> +      .get('/profile')
vou ajustar, obg

2021-07-25 21:03 UTC, marianaalucena approved these changes

2021-07-26 15:04 UTC, thaynnara007 approved these changes

2021-07-26 15:04 UTC, merged